name: Workflow 

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'

jobs:
  job-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |

      - name: Executar Tarefas
        run: |

  job-agendado:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |

      - name: Executar Tarefas
        run: |

